### ISSUE TITLE
Convert tests to Rspec

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/os-map-ref#2]
Sorry :anguished:, should have made it clear before putting together the gem. To reduce the overhead on developers within the EA, particularly those in the throws of learning new skills like Ruby we've gone _all in_ on certain choices, one of them being _Rspec_ for our test framework.

Therefore when we get the chance we need to convert the current _minitests_ to _Rspec_.

**Comment by reggieb** [comment]
I don't understand why using the default and simpler `minitest` is an overhead, and adding an additional DSL is not.

**Comment by Cruikshanks** [comment]
Just to confirm our discussion, this isn't really about the technical merits of the 2 test frameworks, and I agree I'd rather avoid adding to the gem just to support a different test tool. This is born out of considering the current skills of those who will be responsible for maintaining this gem.

**Comment by reggieb** [comment]
Agreed, and I will make the change when I have some free time.
